--liquibase formatted sql

--changeset reginaldo:1589088050671-1
CREATE TABLE biddings (id INT AUTO_INCREMENT NOT NULL, `description` TEXT NULL, type ENUM("NOTA_PRECO", "MENOR_PRECO") DEFAULT "MENOR_PRECO" NULL, CONSTRAINT PK_BIDDINGS PRIMARY KEY (id));

--changeset reginaldo:1589088050671-2
CREATE TABLE proposals (id INT AUTO_INCREMENT NOT NULL, `provider` VARCHAR(50) NULL, note DECIMAL(19,2) NULL DEFAULT 0.00, price DECIMAL(19,2) NULL DEFAULT 0.00, createdDate VARCHAR(100) NULL, classificator INT(11) NULL, bidding_id INT(11) NOT NULL, CONSTRAINT PK_PROPOSALS PRIMARY KEY (id));

--changeset reginaldo:1589088050671-3
ALTER TABLE proposals ADD CONSTRAINT PK_PROPOSALS_BIDDING_ID FOREIGN KEY (bidding_id) REFERENCES biddings (id) ON UPDATE RESTRICT ON DELETE RESTRICT;