version: "3.7"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: az-desafio-rafael-camilo-backend
    environment:
      - "spring.datasource.initialization-mode=never"
      - "spring.datasource.hikari.connectionTimeout=20000"
      - "spring.datasource.hikari.maximumPoolSize=5"
      - "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
      - "spring.datasource.url=jdbc:mysql://az-desafio-rafael-camilo-database:3306/az_desafio_rafael_camilo"
      - "spring.datasource.username=root"
      - "spring.datasource.password=root"
      - "spring.liquibase.enabled=true"
      - "spring.liquibase.url=jdbc:mysql://az-desafio-rafael-camilo-database:3306/az_desafio_rafael_camilo?useTimezone=true&serverTimezone=UTC"
      - "spring.liquibase.user=root"
      - "spring.liquibase.password=root"
      - "spring.liquibase.change-log=classpath:db/changelog/db.mysql.sql"
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - database

  database:
    image: mysql:latest
    container_name: az-desafio-rafael-camilo-database
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=az_desafio_rafael_camilo
    ports:
      - "3306:3306"
    expose:
      - 3306
    restart: unless-stopped
    networks:
      - database

networks:
  database:
