version: "3.7"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: az-desafio-rafael-camilo-backend
    environment:
      - "spring.datasource.initialization-mode=never"
      - "spring.datasource.hikari.connectionTimeout=20000"
      - "spring.datasource.hikari.maximumPoolSize=5"
      - "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
      - "spring.datasource.url=jdbc:mysql://az-desafio-rafael-camilo-database:3306/az_desafio_rafael_camilo?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC"
      - "spring.datasource.username=root"
      - "spring.datasource.password=root"
      - "spring.liquibase.enabled=false"
    ports:
      - "8080:80"
    expose:
      - 80
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - database

  database:
    image: mysql:latest
    container_name: az-desafio-rafael-camilo-database
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=az_desafio_rafael_camilo
    ports:
      - "3377:3306"
    expose:
      - 3306
    restart: unless-stopped
    networks:
      - database

networks:
  database:
